DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS changes;
DROP TABLE IF EXISTS commits;
DROP TABLE IF EXISTS managementAssignments;
DROP TABLE IF EXISTS workAssignments;
DROP TABLE IF EXISTS goals;
DROP TABLE IF EXISTS phoneNumbers;
DROP TABLE IF EXISTS contributors;
DROP TABLE IF EXISTS projects;

DROP TABLE IF EXISTS goalPriorities;
DROP TABLE IF EXISTS goalTypes;
DROP TABLE IF EXISTS goalStatuses;